function processingMask = identifyPipelineFolders(sourceFolders, config)
%IDENTIFYPIPELINEFOLDERS 選出新 EPI 資料夾及可續做的中間成果資料夾。

    processingMask = false(size(sourceFolders));

    for index = 1:numel(sourceFolders)
        folderPath = sourceFolders(index).Path;

        mriState = epi0.inspectMRIIndexState(folderPath, ...
            config.DeleteFirstIndex, config.DeleteLastIndex);

        xFiles = epi0.listValidXFiles(folderPath);
        unscaledNifti = epi0.listUnscaledConvertedNiftiFiles(folderPath);

        hasSourceEPI0 = isfile(fullfile(folderPath, 'EPI0.nii'));
        looksLikeDeletionCompleted = ...
            mriState.EarlyFileCount == 0 && ...
            mriState.HasIndexAfterDeleteRange;

        processingMask(index) = ...
            sourceFolders(index).DirectFileCount > ...
                config.LargeFolderThreshold || ...
            hasSourceEPI0 || ...
            ~isempty(xFiles) || ...
            ~isempty(unscaledNifti) || ...
            looksLikeDeletionCompleted;
    end
end
