function report = initializeReport(sourceFolders)
%INITIALIZEREPORT 建立每個舊資料夾的處理紀錄。

    emptyReport = struct( ...
        'SourceFolder', '', ...
        'FolderName', '', ...
        'GroupAnimal', '', ...
        'EOrder', NaN, ...
        'InitialFileCount', 0, ...
        'IsPipelineFolder', false, ...
        'EligibleForConversion', false, ...
        'DeletedCount', 0, ...
        'Step1Status', '', ...
        'ConvertedFile', '', ...
        'ScaledFile', '', ...
        'EPI0Created', '', ...
        'Step2To4Status', '', ...
        'AssignedDestination', '', ...
        'MovedTo', '', ...
        'Step6Status', '', ...
        'Status', 'Not processed', ...
        'Message', '');

    report = repmat(emptyReport, numel(sourceFolders), 1);

    for index = 1:numel(sourceFolders)
        report(index).SourceFolder = sourceFolders(index).Path;
        report(index).FolderName = sourceFolders(index).Name;
        report(index).GroupAnimal = sourceFolders(index).GroupAnimal;
        report(index).EOrder = sourceFolders(index).EOrder;
        report(index).InitialFileCount = ...
            sourceFolders(index).DirectFileCount;
    end
end
